name: "godot-ci export"
on: 
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_PATH: /web/${{ github.ref }}

jobs:
  export-web:
    name: build
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p $BUILD_PATH
          rm -rf $BUILD_PATH/*
          godot --headless --verbose --export-release "Web" "$BUILD_PATH/index.html"
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'See changes here: https://global-jam-25.izzy.kiwi/${{ github.ref }}/index.html'
            })
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: web
          path: $BUILD_PATH
